spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  config:
    import: classpath:application-message.yml
---
spring:
  config:
    activate:
      on-profile: dev
    import: classpath:application-message-dev.yml
